### ISSUE TITLE
excessive logging output

### ISSUE THREAD

**Issue by danieleades** [actions-rs-plus/clippy-check#409]
I had a go at using this action for the `rust-mavlink` crate, but ran into some issues. The crate does a massive amount of code-gen, which gets logged in full by the clippy-check action. The volume of logging seems to make everything fall over

see https://github.com/mavlink/rust-mavlink/actions/runs/6605168574/job/17940079156?pr=157

**Comment by kristof-mattei** [comment]
Clippy-check captures the stdout to parse out the messages it is interested in. If you were to run it locally on your machine you would see the same amount of output.

The issue is exacerbated because everything is seemingly on one long line making `text` > 900KB PER `compiler-message` output.

Can you format the code before running clippy? I saw https://github.com/mavlink/rust-mavlink/blob/74243e339a131d8ca08e26f51b900f0d373eae10/build/main.rs#L92 which would reduce the context in the `text` output.

If you're not interested in fixing the clippy issues in the generated code you can also emit `#![allow(clippy::all)]` on top of the file.

(I'm not even sure how GitHub renders annotations on files that aren't part of the codebase.)

**Comment by danieleades** [comment]
thanks for taking a look!

> Can you format the code before running clippy? I saw https://github.com/mavlink/rust-mavlink/blob/74243e339a131d8ca08e26f51b900f0d373eae10/build/main.rs#L92 which would reduce the context in the `text` output.

doesn't seem to help. I'm guessing the formatter runs after clippy sees the output, or something

see https://github.com/mavlink/rust-mavlink/actions/runs/6630404594/job/18011726271?pr=157

> If you're not interested in fixing the clippy issues in the generated code you can also emit #![allow(clippy::all)] on top of the file.

I *am* interested in fixing the issues

**Comment by kristof-mattei** [comment]
@danieleades I just went back and now your build seems to be succeeding! 

Can you elaborate on the fix?

**Comment by danieleades** [comment]
> @danieleades I just went back and now your build seems to be succeeding!
> 
> Can you elaborate on the fix?

the build is passing because i addressed the warnings, so in that sense the clippy check is working.
It hasn't solved all of my problems as the output when the build fails is not really parsable or useful.

that's probably not the fault of this github action- i'm not even sure what sort of output i would expect for generated code

**Comment by kristof-mattei** [comment]
@danieleades Yea this seems to be a GitHub actions issue. The only way we could fix this with THAT amount of text is piping the output to a text and then annotating it like that.

I did end up testing how annotations look like when you annotate text that isn't part of the repo.

It looks like this:

<img width="529" alt="image" src="https://github.com/actions-rs-plus/clippy-check/assets/864376/ed1ccb6a-fdda-4a78-aa1e-6c8ee039054b">


But when you click the link you get nowhere.
